services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=micro
      - POSTGRES_USER=micro
      - POSTGRES_DB=test_app_db
    volumes:
      - pgdata:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  pgdata:

  